saintsbetold/__init__.py
import app, blueprints

saintsbetold/app.py
from os import path, walk

from flask import Flask

from blueprints import blueprints



def create_app(environment=None):
    app = Flask(__name__)

    # Configuration -----------------------------------------------------------
    cwd = path.dirname(path.abspath(__file__))
    config_dir = path.join(cwd, 'config')

    config_files = []
    for (root, dir_names, file_names) in walk(config_dir):
        for file_name in file_names:
            config_files.append(path.join(root, file_name))
    config_files = sorted(config_files)

    for config_file in config_files:
        app.config.from_pyfile(config_file)

        if environment:
            if environment in config_file:
                break # only go as deep as the runtime

    # Blueprints --------------------------------------------------------------
    app.register_blueprint(blueprints)

    return app

saintsbetold/blueprints.py
from flask import Blueprint, render_template, current_app

blueprints = Blueprint('page', __name__, template_folder='templates/pages')


# Homepage --------------------------------------------------------------------

@blueprints.route('/')
def home():
    return render_template('index.html')


# Legal Policy ----------------------------------------------------------------

@blueprints.route('/legal/privacy/')
def privacy():
    return render_template('legal/privacy.html')


@blueprints.route('/legal/terms/')
def terms():
    return render_template('legal/terms.html')


# Sitemap

@blueprints.route('/sitemap.xml')
def sitemap():
    pages = [rule for rule in current_app.url_map.iter_rules() if rule.arguments.__len__() == 0]
    return render_template('sitemap.xml', pages=pages)

saintsbetold/templates/layout/app.html
{% import "macros/services.jinja2" as services with context %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="description"
              content="{% block meta_description %}Saints Be Told Ltd. is a marketing and advertising publishing company incorporated in the state of Michigan and operating in the city of Allegan.{% endblock %}">

        <title>
            {% block title %}{% endblock %} - {{ config['TITLE'] }}
        </title>

        <link rel="stylesheet" href="{{ url_for('static', filename='css/normalize.css') }}">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/saintsbetold.css') }}">
    </head>
    <body class="home">
        {% include 'layout/header.html' %}
        {% block main %}{% endblock %}
        {% include 'layout/footer.html' %}

        {% if config['ANALYTICS_GOOGLE'] %}
            {{ services.google_analytics(config['ANALYTICS_GOOGLE'])|safe }}
        {% endif %}
        {% if config['ANALYTICS_HEAP'] %}
            {{ services.heap_analytics(config['ANALYTICS_HEAP'])|safe }}
        {% endif %}
    </body>
</html>

saintsbetold/templates/layout/footer.html
{% set love %}
    {% if config['GITHUB_URL'] %}
        <a href="{{ config['GITHUB_URL']|safe }}" target="_blank">&hearts;</a>
    {% else %}
        &hearts;
    {% endif %}
{% endset %}

<footer class="app-footer">
    <ul class="footer-links right">
        Made with {{ love|safe }} in <a href="http://www.cityofallegan.org/" target="_blank">Allegan</a>, <a href="http://www.michigan.org/" target="_blank">Michigan</a>.
    </ul>
    
    <ul class="footer-links">
        <li>&copy; 2016 Saints Be Told Ltd.</li>
        <li><a href="{{ url_for('page.terms') }}">Terms</a></li>
        <li><a href="{{ url_for('page.privacy') }}">Privacy</a></li> 
        <li><a href="{{ url_for('page.sitemap') }}">Sitemap</a></li>
    </ul>
</footer>

<!-- <a href="https://heapanalytics.com/?utm_source=badge"><img style="width:108px;height:41px" src="//heapanalytics.com/img/badgeLight.png" alt="Heap | Mobile and Web Analytics" /></a> -->

saintsbetold/templates/layout/header.html
<header class="app-header">
    <a href="/" class="logo-link">
        <svg class="logomorph" xmlns="http://www.w3.org/2000/svg"
             width="300px" height="30px" viewBox="0 0 300 15">
          <text x="15" y="20" 
                font-family="sans-serif" 
                font-size="30">
            Saints Be Told Ltd.
          </text>
        </svg>
    </a>
</header>

saintsbetold/templates/layout/page.html
<main>
    <header class="page-header">
        <h1 class="page-header-title">
            We are
            <strong>Saints Be Told Ltd.</strong>
        </h1>
        <h2 class="page-header-sub-title">
            We are dedicated to serving the Allegan area.
        </h2>
    </header>
</main>

saintsbetold/templates/macros/services.jinja2
{% macro google_analytics(id)-%}
<script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

    ga('create', "{{ id }}", 'auto');
    ga('send', 'pageview');
</script>
{% endmacro %}

{% macro heap_analytics(id) %}
<script type="text/javascript">
    window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
    heap.load("{{ id }}");
</script>
{% endmacro %}

saintsbetold/templates/pages/index.html
{% extends 'layout/app.html' %}

{% block title %}Homepage{% endblock %}

{% block main %}
<main>
    <header class="page-header">
        <h1 class="page-header-title">
            We are
            <strong>Saints Be Told Ltd.</strong>
        </h1>
        <h2 class="page-header-sub-title">
            We are dedicated to serving the Allegan area.
        </h2>
    </header>
</main>
{% endblock %}

saintsbetold/templates/pages/legal/privacy.html
{% extends 'layout/app.html' %}

{% block main %}
<h1>Privacy Policy</h1>

<p>Your privacy is important to us.</p>

<p>It is Saints Be Told Ltd.'s policy to respect your privacy regarding any information we may collect while operating our website. Accordingly, we have developed this privacy policy in order for you to understand how we collect, use, communicate, disclose and otherwise make use of personal information. We have outlined our privacy policy below.</p>

<ul>
    <li>We will collect personal information by lawful and fair means and, where appropriate, with the knowledge or consent of the individual concerned.</li>
    <li>Before or at the time of collecting personal information, we will identify the purposes for which information is being collected.</li>
    <li>We will collect and use personal information solely for fulfilling those purposes specified by us and for other ancillary purposes, unless we obtain the consent of the individual concerned or as required by law.</li>
    <li>Personal data should be relevant to the purposes for which it is to be used, and, to the extent necessary for those purposes, should be accurate, complete, and up-to-date.</li>
    <li>We will protect personal information by using reasonable security safeguards against loss or theft, as well as unauthorized access, disclosure, copying, use or modification.</li>
    <li>We will make readily available to customers information about our policies and practices relating to the management of personal information.</li>
    <li>We will only retain personal information for as long as necessary for the fulfilment of those purposes.</li>
</ul>

<p>We are committed to conducting our business in accordance with these principles in order to ensure that the confidentiality of personal information is protected and maintained. Saints Be Told Ltd. may change this privacy policy from time to time at Saints Be Told Ltd.'s sole discretion.</p>

<hr>

<p>Last Revised 2016 August 19.</p>
{% endblock %}